// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB6JgulOU15cKe7V-oNcboWScX6_DbuZY',
    appId: '1:787375402089:web:bb98d7aa19147eb09586f8',
    messagingSenderId: '787375402089',
    projectId: 'roommateapp-fbb4f',
    authDomain: 'roommateapp-fbb4f.firebaseapp.com',
    storageBucket: 'roommateapp-fbb4f.firebasestorage.app',
    measurementId: 'G-GC4SG52RHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1eJF6TKcEoYgyJRUMddZBp2qAdUzrN7o',
    appId: '1:787375402089:android:9c7cba750f2462b09586f8',
    messagingSenderId: '787375402089',
    projectId: 'roommateapp-fbb4f',
    storageBucket: 'roommateapp-fbb4f.firebasestorage.app',
    databaseURL: 'https://roommateapp-fbb4f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwU6v-jypSd_xBO1AGrn35w9nBYmYWDEY',
    appId: '1:787375402089:ios:dcc86f98640e6f4d9586f8',
    messagingSenderId: '787375402089',
    projectId: 'roommateapp-fbb4f',
    storageBucket: 'roommateapp-fbb4f.firebasestorage.app',
    databaseURL: 'https://roommateapp-fbb4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.roommateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwU6v-jypSd_xBO1AGrn35w9nBYmYWDEY',
    appId: '1:787375402089:ios:dcc86f98640e6f4d9586f8',
    messagingSenderId: '787375402089',
    projectId: 'roommateapp-fbb4f',
    storageBucket: 'roommateapp-fbb4f.firebasestorage.app',
    databaseURL: 'https://roommateapp-fbb4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.roommateapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB6JgulOU15cKe7V-oNcboWScX6_DbuZY',
    appId: '1:787375402089:web:342b772a1dd356f99586f8',
    messagingSenderId: '787375402089',
    projectId: 'roommateapp-fbb4f',
    authDomain: 'roommateapp-fbb4f.firebaseapp.com',
    storageBucket: 'roommateapp-fbb4f.firebasestorage.app',
    databaseURL: 'https://roommateapp-fbb4f-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-YL5X7431RJ',
  );
}
