"""
Generate RoomMateApp QA Test Cases v3 — Separate sheets per function.
"""
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = openpyxl.Workbook()
# Remove default sheet
wb.remove(wb.active)

# ── Colors ──
BLUE_HEADER   = "1F5C99"
YELLOW_JIRA   = "FFFF00"
LIGHT_BLUE_PC = "BDD7EE"
LIGHT_GREEN_MOB="E2EFDA"
LIGHT_ORANGE_TAB="FCE4D6"
WHITE         = "FFFFFF"
LIGHT_GRAY    = "F2F2F2"
UNIT_BG       = "7030A0"
FRONT_END_BG  = "4472C4"
BACK_END_BG   = "ED7D31"
INTEG_BG      = "70AD47"

def make_fill(hex_color):
    return PatternFill("solid", fgColor=hex_color)

def thin_border():
    s = Side(style="thin", color="BFBFBF")
    return Border(left=s, right=s, top=s, bottom=s)

def header_font(bold=True, color="FFFFFF", size=10):
    return Font(name="Calibri", bold=bold, color=color, size=size)

def cell_font(bold=False, color="000000", size=10):
    return Font(name="Calibri", bold=bold, color=color, size=size)

def wrap_align(horizontal="center", vertical="center"):
    return Alignment(horizontal=horizontal, vertical=vertical, wrap_text=True)

def create_sheet(wb, title, section_label, section_color, subsections):
    ws = wb.create_sheet(title=title)
    col_widths = {1:8,2:20,3:28,4:48,5:40,6:22,7:7,8:7,9:8,10:8,11:9,12:11,13:7,14:11,15:10}
    for col, width in col_widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width

    # Row 1 — Title
    ws.row_dimensions[1].height = 22
    ws.merge_cells("A1:F1")
    c = ws["A1"]
    c.value = f"Test Case: RoomMateApp — {section_label}"
    c.fill = make_fill(BLUE_HEADER)
    c.font = header_font(size=12)
    c.alignment = wrap_align("left")

    groups = [
        ("G1:J1", "PC", LIGHT_BLUE_PC, "000000"),
        ("K1:L1", "Mobile", LIGHT_GREEN_MOB, "000000"),
        ("M1:N1", "Tablet", LIGHT_ORANGE_TAB, "000000"),
        ("O1:O1", "", YELLOW_JIRA, "000000"),
    ]
    for span, label, color, fc in groups:
        if ":" in span and span.split(":")[0] != span.split(":")[1]:
            ws.merge_cells(span)
        cell = ws[span.split(":")[0]]
        cell.value = label
        cell.fill = make_fill(color)
        cell.font = Font(name="Calibri", bold=True, color=fc, size=10)
        cell.alignment = wrap_align()

    # Row 2 — Headers
    ws.row_dimensions[2].height = 36
    headers = [
        "ID", "Items", "Sub-items", "Steps to Execute",
        "Expected Output", "Test Data/\nParameters",
        "IE11", "FF", "Chrome", "Safari",
        "IphoneX", "Samsung\nS7", "Ipad", "HTC\nTablet", "Jira Bug"
    ]
    header_fills = [BLUE_HEADER]*6 + [BLUE_HEADER]*4 + [BLUE_HEADER]*2 + [BLUE_HEADER]*2 + [YELLOW_JIRA]
    for col_idx, (hdr, fill_color) in enumerate(zip(headers, header_fills), start=1):
        c = ws.cell(row=2, column=col_idx)
        c.value = hdr
        c.fill = make_fill(fill_color)
        fc = "000000" if fill_color == YELLOW_JIRA else "FFFFFF"
        c.font = header_font(color=fc, size=10)
        c.alignment = wrap_align()
        c.border = thin_border()

    # Write data
    row = 3
    for sub_label, sub_color, cases in subsections:
        # Subsection header
        ws.row_dimensions[row].height = 16
        ws.merge_cells(f"A{row}:O{row}")
        c = ws[f"A{row}"]
        c.value = "  " + sub_label
        c.fill = make_fill(sub_color)
        c.font = Font(name="Calibri", bold=True, color="FFFFFF", size=9, italic=True)
        c.alignment = wrap_align("left")
        c.border = thin_border()
        row += 1

        for case in cases:
            tc_id, items, sub, steps, exp, data_, ie, ff, ch, sa, iph, sam, ipad_, htc, jira = case
            bg = WHITE if (row % 2 == 0) else LIGHT_GRAY
            ws.row_dimensions[row].height = max(15, min(120, (steps.count("\n") + 1) * 15))
            vals = [tc_id, items, sub, steps, exp, data_, ie, ff, ch, sa, iph, sam, ipad_, htc, jira]
            for col_idx, val in enumerate(vals, start=1):
                c = ws.cell(row=row, column=col_idx)
                c.value = val
                c.fill = make_fill(bg)
                c.font = cell_font(size=9)
                c.border = thin_border()
                if col_idx in (1,7,8,9,10,11,12,13,14,15):
                    c.alignment = wrap_align("center")
                elif col_idx == 2:
                    c.alignment = wrap_align("center")
                else:
                    c.alignment = wrap_align("left")
            row += 1

    # Freeze
    ws.freeze_panes = "A3"
    ws.auto_filter.ref = "A2:O2"
    return ws

def tc(tc_id, items, sub, steps, exp, data_="", ie="", ff="", ch="", sa="",
       iph="", sam="", ipad_="", htc="", jira=""):
    return (tc_id, items, sub, steps, exp, data_, ie, ff, ch, sa, iph, sam, ipad_, htc, jira)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 1: MODELS
# ═══════════════════════════════════════════════════════════════════════════════
models_subs = [
    ("PostModel", "1F5C99", [
        tc("TC_001", "PostModel", "fromDocument với đầy đủ dữ liệu",
           "1. Tạo DocumentSnapshot đầy đủ fields\n2. Gọi PostModel.fromDocument(doc)",
           "PostModel đúng: id, title, location, province, district, roomType, amenities, price, area, capacity...",
           "id: 'post1'\ntitle: 'Phòng trọ Q3'\nprice: 3500000"),
        tc("TC_002", "PostModel", "fromDocument với dữ liệu thiếu/null",
           "1. Tạo doc thiếu nhiều field\n2. Gọi fromDocument",
           "Trả về PostModel default. Không throw exception.",
           "data: {}"),
        tc("TC_003", "PostModel", "parseInt xử lý String",
           "1. price='3500000', area='25', capacity='2'\n2. Gọi fromDocument",
           "parseInt chuyển String→int. price=3500000, area=25, capacity=2.",
           "price: '3500000'\narea: '25'\ncapacity: '2'"),
        tc("TC_004", "PostModel", "parseStringList null/empty",
           "1. amenities=null\n2. Gọi fromDocument",
           "Parse thành [].",
           "amenities: null"),
        tc("TC_005", "PostModel", "parseImageUrls fallback imageUrl",
           "1. imageUrls=[], imageUrl='https://ex.com/img.jpg'\n2. Gọi fromDocument",
           "imageUrls = [imageUrl].",
           "imageUrls: []\nimageUrl: 'https://ex.com/img.jpg'"),
        tc("TC_006", "PostModel", "toMap đúng định dạng",
           "1. Tạo PostModel đầy đủ\n2. Gọi toMap()",
           "Map đúng key-value. createdAt/updatedAt = serverTimestamp.",
           "PostModel đầy đủ"),
        tc("TC_007", "PostModel", "copyWith thay đổi 1 field",
           "1. PostModel gốc\n2. copyWith(title: 'New Title')",
           "title='New Title'. Các field khác giữ nguyên.",
           "PostModel gốc\nNew Title"),
    ]),
    ("UserModel", "1F5C99", [
        tc("TC_008", "UserModel", "fromDocument đầy đủ",
           "1. Doc đầy đủ\n2. Gọi fromDocument",
           "UserModel đúng uid, fullName, email, phone, address, gender, age, habits...",
           "UserModel đầy đủ"),
        tc("TC_009", "UserModel", "profileCompleted fallback _computeProfileCompleted",
           "1. profileCompleted='true' (String)\n2. Gọi fromDocument",
           "_computeProfileCompleted: nếu address+gender+habits+criteria đều có → true.",
           "profileCompleted: 'true'\naddress:'Q3'\ngender:'Nam'\nhabits:['clean']"),
        tc("TC_010", "UserModel", "_computeProfileCompleted false khi thiếu",
           "1. address='', habits=[]\n2. Gọi fromDocument",
           "profileCompleted = false.",
           "address: ''\nhabits: []\nroommateCriteria: []"),
        tc("TC_011", "UserModel", "fromMap parse Map",
           "1. Map<String, dynamic>\n2. UserModel.fromMap(map, uid)",
           "Trả về UserModel đúng. age có thể null.",
           "uid: 'user1'\nfullName: 'Nguyen Van A'"),
        tc("TC_012", "UserModel", "toMap xuất Map",
           "1. Tạo UserModel\n2. toMap()",
           "Map key: fullName, email, phone, address, age, habits...",
           "UserModel đầy đủ"),
        tc("TC_013", "UserModel", "copyWith age nullable",
           "1. Age=25\n2. copyWith(age: null)",
           "age = null.",
           "UserModel age=25\ncopyWith age: null"),
    ]),
    ("ExpenseModel / ExpenseShareModel", "1F5C99", [
        tc("TC_014", "ExpenseModel", "fromDocument splitType='custom'",
           "1. doc splitType='custom'\n2. Gọi fromDocument",
           "splitType = SplitType.custom.",
           "splitType: 'custom'"),
        tc("TC_015", "ExpenseModel", "fromDocument parse customSplits",
           "1. customSplits {'A':200000,'B':400000}\n2. fromDocument",
           "customSplits = Map<String, double>.",
           "customSplits: {'A':200000,'B':400000}"),
        tc("TC_016", "ExpenseModel", "toMap splitType string",
           "1. SplitType.custom\n2. toMap()",
           "map['splitType'] = 'custom'.",
           "ExpenseModel custom"),
        tc("TC_017", "ExpenseModel", "copyWith SplitType",
           "1. splitType=equal\n2. copyWith(splitType: SplitType.custom)",
           "splitType = custom.",
           "ExpenseModel equal"),
        tc("TC_018", "ExpenseShareModel", "fromDocument amountOwed từ num?",
           "1. amountOwed=150000\n2. fromDocument",
           "amountOwed = 150000.0. null→0.0.",
           "amountOwed: 150000"),
        tc("TC_019", "ExpenseShareModel", "fromDocument isPaid/isArchived bool?",
           "1. Thiếu isPaid, isArchived\n2. fromDocument",
           "isPaid=false, isArchived=false.",
           "isPaid: null\nisArchived: null"),
        tc("TC_020", "ExpenseShareModel", "toMap paidAt nullable",
           "1. paidAt=DateTime(2026,5,31)\n2. paidAt=null\n3. toMap()",
           "paidAt != null → Timestamp. null → null.",
           "paidAt: 2026-05-31 / null"),
        tc("TC_021", "ExpenseShareModel", "copyWith giữ nguyên isArchived",
           "1. isArchived=true\n2. copyWith(amountOwed:50000)",
           "isArchived=true. amountOwed=50000.",
           "isArchived=true"),
    ]),
    ("ChatMessageModel / ChatConversationModel", "1F5C99", [
        tc("TC_022", "ChatMessageModel", "fromMap đầy đủ",
           "1. Map đầy đủ\n2. ChatMessageModel.fromMap(id, map)",
           "Message đúng: senderId, senderName, text, createdAt, isRead.",
           "id:'msg1'\nsenderId:'userA'\ntext:'Hello'"),
        tc("TC_023", "ChatMessageModel", "fromMap createdAt ms",
           "1. createdAt=1717000000000\n2. fromMap",
           "createdAt = DateTime từ ms. null→epoch.",
           "createdAt: 1717000000000"),
        tc("TC_024", "ChatMessageModel", "fromMap dữ liệu thiếu",
           "1. map rỗng\n2. fromMap",
           "senderId='', text='', isRead=false, createdAt=epoch.",
           "map: {}"),
        tc("TC_025", "ChatMessageModel", "toMap msSinceEpoch",
           "1. ChatMessageModel\n2. toMap()",
           "map['createdAt'] = millisecondsSinceEpoch.",
           "ChatMessageModel"),
        tc("TC_026", "ChatConversationModel", "fromMap đầy đủ",
           "1. Map đầy đủ\n2. fromMap",
           "Conversation đúng: id, otherUserId, otherUserName, lastMessage...",
           "id:'conv1'\notherUserId:'user2'"),
        tc("TC_027", "ChatConversationModel", "fromMap lastMessageAt",
           "1. lastMessageAt=1717000000000\n2. fromMap",
           "lastMessageAt = DateTime từ ms. null→epoch.",
           "lastMessageAt: 1717000000000"),
        tc("TC_028", "ChatConversationModel", "fromMap unreadCount",
           "1. unreadCount='5'\n2. fromMap",
           "unreadCount=5. null→0.",
           "unreadCount: '5'"),
    ]),
    ("RoomSearchFilterModel", "1F5C99", [
        tc("TC_029", "RoomSearchFilterModel", "hasActiveFilters true/false",
           "1. Filter mặc định\n2. hasActiveFilters=false\n3. Thêm keyword→re-check",
           "false khi default. true khi có bất kỳ filter.",
           "Default / có keyword"),
        tc("TC_030", "RoomSearchFilterModel", "selectedPriceRange id đúng",
           "1. priceRangeId='lte_2'\n2. selectedPriceRange",
           "PriceRangeOption(id='lte_2', maxPrice=2000000). null khi rỗng.",
           "priceRangeId: 'lte_2'"),
        tc("TC_031", "RoomSearchFilterModel", "summaryText tóm tắt",
           "1. province + district\n2. summaryText",
           "'Hồ Chí Minh • Quận 1'. Ko filter→'Mở bộ lọc...'.",
           "province:'Hồ Chí Minh'\ndistrict:'Quận 1'"),
        tc("TC_032", "RoomSearchFilterModel", "matchesPost keyword",
           "1. Post title='Phòng trọ Q3'\n2. Filter keyword='phòng'\n3. matchesPost",
           "true. Case-insensitive.",
           "Post title:'Phòng trọ Q3'\nFilter:'phòng'"),
        tc("TC_033", "RoomSearchFilterModel", "matchesPost price range",
           "1. Post price=3000000\n2. Filter '2_3'\n3. matchesPost",
           "true nếu price trong [2tr,3tr].",
           "Post price:3000000\nFilter:'2_3'"),
        tc("TC_034", "RoomSearchFilterModel", "matchesPost amenities AND",
           "1. Post amenities ['Wifi','Máy lạnh']\n2. Filter cả 2",
           "true vì post có cả 2.",
           "Filter: ['Wifi','Máy lạnh']"),
        tc("TC_035", "RoomSearchFilterModel", "matchesPost case-insensitive",
           "1. Post province='Hồ Chí Minh'\n2. Filter 'hồ chí minh'",
           "true. So sánh lowercase.",
           "Post:'Hồ Chí Minh'\nFilter:'hồ chí minh'"),
        tc("TC_036", "RoomSearchFilterModel", "fromMap/toMap roundtrip",
           "1. Filter→toMap()\n2. fromMap→filter2\n3. So sánh",
           "filter2 = filter gốc.",
           "RoomSearchFilterModel đầy đủ"),
        tc("TC_037", "RoomSearchFilterModel", "priceRanges 9 mức",
           "1. Kiểm tra priceRanges",
           "9 mức. 'lte_2': maxPrice=2000000.",
           "length==9"),
    ]),
    ("RoommateRequestModel / RoomGroupModel / Other Models", "1F5C99", [
        tc("TC_038", "RoommateRequestModel", "fromDocument parse status",
           "1. status='accepted'\n2. fromDocument",
           "RoommateRequestStatus.accepted. 'pending'/'rejected'→tương ứng.",
           "status:'accepted'"),
        tc("TC_039", "RoommateRequestModel", "fromDocument parse inviteType",
           "1. inviteType='profile_invite'\n2. fromDocument",
           "profileInvite. Khác→postRequest.",
           "inviteType:'profile_invite'"),
        tc("TC_040", "RoommateRequestModel", "toMap inviteType string",
           "1. profileInvite\n2. toMap()",
           "'profile_invite'. postRequest→'post_request'.",
           "profileInvite"),
        tc("TC_041", "RoommateRequestModel", "copyWith status",
           "1. status=pending\n2. copyWith(status: accepted)",
           "status=accepted. Các field khác giữ nguyên.",
           "RoommateRequestModel pending"),
        tc("TC_042", "RoomGroupModel", "fromDocument default status",
           "1. Không có status\n2. fromDocument",
           "status='active'.",
           "status: null"),
        tc("TC_043", "RoomGroupModel", "toMap memberIds",
           "1. memberIds=['A','B']\n2. toMap()",
           "map['memberIds']=['A','B'].",
           "memberIds:['A','B']"),
        tc("TC_044", "RoomGroupModel", "copyWith disbanded",
           "1. status='active'\n2. copyWith(status:'disbanded')",
           "status='disbanded'.",
           "RoomGroupModel active"),
        tc("TC_045", "ProfileHabitCatalog", "findById tồn tại",
           "1. findById('clean')",
           "ProfileHabitModel(id='clean', label='Sạch sẽ').",
           "id:'clean'"),
        tc("TC_046", "ProfileHabitCatalog", "findById không tồn tại",
           "1. findById('invalid')",
           "null.",
           "id:'invalid'"),
        tc("TC_047", "RoommateCriteriaModel", "Khởi tạo id + label",
           "1. RoommateCriteriaModel(id:'quiet', label:'Yên tĩnh')",
           "id='quiet', label='Yên tĩnh'.",
           "id:'quiet'\nlabel:'Yên tĩnh'"),
        tc("TC_048", "UserSession", "Khởi tạo user + role + profile nullable",
           "1. UserSession(user, 'user', null)",
           "Đúng user, role='user', profile=null.",
           "role:'user'\nprofile:null"),
    ]),
]

create_sheet(wb, "01 - Models", "UNIT TESTS — MODELS", UNIT_BG, models_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 2: REPOSITORIES
# ═══════════════════════════════════════════════════════════════════════════════
repos_subs = [
    ("AuthRepository", "1F5C99", [
        tc("TC_049", "AuthRepository", "login gọi signInWithEmailAndPassword",
           "1. repository.login(email, password)\n2. Kiểm tra tham số",
           "signInWithEmailAndPassword với email/password đã trim().",
           "Email:' test@ex.com '\nPassword:' pass '"),
        tc("TC_050", "AuthRepository", "register tạo user + Firestore doc",
           "1. register với đầy đủ\n2. Kiểm tra user.updateDisplayName\n3. Firestore.set",
           "Tài khoản tạo. Firestore doc set đúng fields.",
           "fullName:'Nguyen Van A'\nemail:'test@test.com'\npassword:'Test@1234'"),
        tc("TC_051", "AuthRepository", "getUserRole không có doc → tạo mới",
           "1. getUserRole uid chưa có doc\n2. ensureUserDocument tạo doc",
           "Trả về 'user'. Document tạo nếu chưa tồn tại.",
           "uid:'new_user_uid'"),
        tc("TC_052", "AuthRepository", "getUserRole FirebaseException fallback",
           "1. Firestore throw exception\n2. getUserRole",
           "Bắt exception→trả về 'user'.",
           "FirebaseException"),
        tc("TC_053", "AuthRepository", "signInWithGoogle tạo user mới",
           "1. Google sign-in thành công\n2. Firestore doc chưa tồn tại",
           "Tạo doc mới role='user', profileCompleted=false.",
           "Google user mới"),
        tc("TC_054", "AuthRepository", "signInWithGoogle user đã tồn tại",
           "1. Google sign-in user đã có doc\n2. Kiểm tra không ghi đè",
           "Không set. Giữ nguyên doc.",
           "Google user đã tồn tại"),
        tc("TC_055", "AuthRepository", "resetPassword trim email",
           "1. resetPassword(' test@ex.com ')",
           "sendPasswordResetEmail với 'test@ex.com'.",
           "Email:' test@ex.com '"),
        tc("TC_056", "AuthRepository", "logout gọi signOut",
           "1. logout()",
           "_auth.signOut() được gọi.",
           "—"),
    ]),
    ("PostRepository", "1F5C99", [
        tc("TC_057", "PostRepository", "createPost không user→throw",
           "1. currentUser=null\n2. createPost",
           "Throw 'Người dùng chưa đăng nhập'.",
           "currentUser: null"),
        tc("TC_058", "PostRepository", "createPost upload ảnh + tạo post",
           "1. currentUser hợp lệ\n2. Upload 2 ảnh\n3. Tạo post",
           "Upload Cloudinary. Firestore add doc.",
           "2 ảnh\ntitle:'Phòng trọ Q3'\nprice:3500000"),
        tc("TC_059", "PostRepository", "createPost giới hạn 5 ảnh",
           "1. Upload 7 ảnh",
           "Chỉ 5 ảnh đầu được upload.",
           "7 image files"),
        tc("TC_060", "PostRepository", "updatePost không phải chủ→throw",
           "1. currentUser != data['ownerId']\n2. updatePost",
           "Throw 'Không có quyền sửa'.",
           "postId của người khác"),
        tc("TC_061", "PostRepository", "updatePost với imageFiles mới",
           "1. Có imageFiles mới\n2. Upload Cloudinary\n3. Update",
           "imageUrls mới. imageUrl=imageUrls.first.",
           "3 image files mới"),
        tc("TC_062", "PostRepository", "deletePost xóa post + requests",
           "1. currentUser là chủ\n2. Có roommate_requests liên quan",
           "Batch delete post + requests.",
           "postId hợp lệ\ncó 2 requests"),
        tc("TC_063", "PostRepository", "_buildFilteredQuery với province+district",
           "1. Filter province+district\n2. Build query",
           "Query.where('province').where('district').orderBy('createdAt',desc).",
           "province:'Hồ Chí Minh'\ndistrict:'Quận 1'"),
        tc("TC_064", "PostRepository", "_buildFilteredQuery price range",
           "1. priceRangeId='2_3'\n2. Build query",
           "Query.where('price',>=2tr).where('price',<=3tr).orderBy('price').",
           "priceRangeId:'2_3'"),
        tc("TC_065", "PostRepository", "getPostsPageStream→PostsPageResult",
           "1. Gọi getPostsPageStream\n2. Subscribe",
           "Stream emits PostsPageResult. nextCursor=last doc nếu >= pageSize.",
           "RoomSearchFilterModel default"),
        tc("TC_066", "PostRepository", "loadMorePosts startAfter+limit",
           "1. loadMorePosts(lastDoc, filter)",
           "Query.startAfterDocument(lastDoc).limit(pageSize).",
           "lastDoc hợp lệ"),
    ]),
    ("ExpenseRepository", "1F5C99", [
        tc("TC_067", "ExpenseRepository", "addExpense tạo id mới",
           "1. addExpense(expense)\n2. Kiểm tra docRef.id",
           "DocRef.id tự sinh. Model copy với id mới.",
           "ExpenseModel không id"),
        tc("TC_068", "ExpenseRepository", "addExpenseWithShares batch",
           "1. addExpenseWithShares(expense, shares)",
           "Batch set expense + tất cả shares.",
           "1 expense + 2 shares"),
        tc("TC_069", "ExpenseRepository", "getExpenseById null nếu ko tồn tại",
           "1. getExpenseById('fake')",
           "null.",
           "expenseId:'fake'"),
        tc("TC_070", "ExpenseRepository", "getExpensesByRoomGroup stream",
           "1. getExpensesByRoomGroup('group1')",
           "Stream query roomGroupId='group1'. orderBy createdAt desc.",
           "roomGroupId:'group1'"),
        tc("TC_071", "ExpenseRepository", "getDebtsOwedByUser lọc isArchived",
           "1. getDebtsOwedByUser('userA','group1')",
           "Query fromUserId, isPaid=false. Filter isArchived != true.",
           "fromUserId:'userA'\nroomGroupId:'group1'"),
        tc("TC_072", "ExpenseRepository", "markShareAsPaid",
           "1. markShareAsPaid('share1')",
           "isPaid=true, paidAt=serverTimestamp.",
           "shareId:'share1'"),
        tc("TC_073", "ExpenseRepository", "updateExpense archive cũ + tạo mới",
           "1. updateExpense với newShares",
           "Old→isArchived=true. New→set. Batch.",
           "2 old + 3 new shares"),
        tc("TC_074", "ExpenseRepository", "deleteExpense xóa expense+shares",
           "1. deleteExpense('exp1')",
           "Batch delete expense + shares.",
           "expenseId:'exp1'\ncó 3 shares"),
        tc("TC_075", "ExpenseRepository", "getExpensesByMonth Timestamp range",
           "1. getExpensesByMonth('grp1',2026,5)",
           "Query createdAt >= first day, < first day next month.",
           "roomGroupId:'grp1'\nyear:2026\nmonth:5"),
        tc("TC_076", "ExpenseRepository", "settleAllDebts batch update",
           "1. settleAllDebts('userA','userB','grp1')",
           "Batch update all shares isPaid=true, paidAt=timestamp.",
           "fromUserId:'userA'\ntoUserId:'userB'\nroomGroupId:'grp1'"),
    ]),
    ("ChatRepository", "1F5C99", [
        tc("TC_077", "ChatRepository", "getConversationId sort uid",
           "1. getConversationId('userB','userA')",
           "'userA_userB'.",
           "uid1:'userB'\nuid2:'userA'"),
        tc("TC_078", "ChatRepository", "ensureConversation tạo node mới",
           "1. Conversation chưa tồn tại\n2. ensureConversation('conv1','user2')",
           "Tạo node chats/conv1 với participantAId, participantBId, createdAt.",
           "conversationId:'conv1'\notherUserId:'user2'"),
        tc("TC_079", "ChatRepository", "ensureConversation đã tồn tại→skip",
           "1. Conversation đã có participantAId\n2. ensureConversation",
           "Không ghi đè.",
           "Đã tồn tại"),
        tc("TC_080", "ChatRepository", "sendMessage tạo message+metadata",
           "1. sendMessage('conv1','userB','Hello','User B','avatar')",
           "Push message. Update user_conversations cả 2 user.",
           "conversationId:'conv1'\nreceiverId:'userB'\ntext:'Hello!'"),
        tc("TC_081", "ChatRepository", "sendMessage tăng unreadCount receiver",
           "1. Gửi tin nhắn\n2. Kiểm tra receiver",
           "user_conversations/[receiverId]/unreadCount = increment(1).",
           "receiverId:'userB'"),
        tc("TC_082", "ChatRepository", "getMessagesStream parse+sort",
           "1. Có messages\n2. getMessagesStream\n3. Subscribe",
           "Stream emits List<ChatMessageModel> sorted by createdAt.",
           "conversationId:'conv1'\ncó 5 messages"),
        tc("TC_083", "ChatRepository", "getConversationsStream ko user→error",
           "1. currentUser=null\n2. getConversationsStream",
           "Stream error: 'Not authenticated'.",
           "currentUser: null"),
        tc("TC_084", "ChatRepository", "markAsRead reset unread+set isRead",
           "1. Có tin chưa đọc của người khác\n2. markAsRead('conv1')",
           "unreadCount=0. isRead=true cho messages senderId != currentUid.",
           "conversationId:'conv1'\nunreadCount>0"),
        tc("TC_085", "ChatRepository", "clearStreamCaches clear maps",
           "1. clearStreamCaches()",
           "_messageStreams.clear()+_conversationStreams.clear().",
           "—"),
    ]),
    ("Other Repositories", "1F5C99", [
        tc("TC_086", "RoommateProfileRepository", "getSuggestedProfilesStream no user→empty",
           "1. currentUser.uid=null\n2. getSuggestedProfilesStream",
           "Stream.empty().",
           "currentUser: null"),
        tc("TC_087", "RoommateProfileRepository", "sendInvite tự mời→throw",
           "1. targetUserId=currentUser.uid\n2. sendInvite",
           "Throw 'Bạn không thể mời chính mình'.",
           "targetUserId==currentUser.uid"),
        tc("TC_088", "RoommateProfileRepository", "sendInvite duplicate→throw",
           "1. Đã có pending invite\n2. sendInvite lần nữa",
           "Throw 'đã gửi lời mời rồi'.",
           "Duplicate invite"),
        tc("TC_089", "HomeSearchFilterRepository", "getSavedFilter ko user→default",
           "1. currentUserId=null\n2. getSavedFilter",
           "RoomSearchFilterModel() mặc định.",
           "currentUserId: null"),
        tc("TC_090", "HomeSearchFilterRepository", "saveFilter ko user→throw",
           "1. currentUserId=null\n2. saveFilter(filter)",
           "Throw 'Người dùng chưa đăng nhập'.",
           "currentUserId: null"),
        tc("TC_091", "HomeSearchFilterRepository", "saveFilter merge=true",
           "1. saveFilter(filter)",
           "Set roomSearchFilter+updatedAt. merge:true.",
           "RoomSearchFilterModel"),
        tc("TC_092", "HomeSearchFilterRepository", "clearSavedFilter reset default",
           "1. clearSavedFilter()",
           "roomSearchFilter=RoomSearchFilterModel().toMap().",
           "—"),
        tc("TC_093", "RoommateRequestRepository", "sendRequest tạo pending",
           "1. sendRequest(postId, message)",
           "Tạo roommate_request status='pending', requesterId=currentUser.uid.",
           "postId:'post1'\nmessage:'Cho mình ở ghép với'"),
        tc("TC_094", "RoommateRequestRepository", "acceptRequest update status",
           "1. acceptRequest('req1')",
           "status='accepted', respondedAt=serverTimestamp.",
           "requestId:'req1'"),
        tc("TC_095", "RoommateRequestRepository", "rejectRequest update status",
           "1. rejectRequest('req1')",
           "status='rejected', respondedAt=serverTimestamp.",
           "requestId:'req1'"),
        tc("TC_096", "RoomGroupRepository", "createGroupAfterAcceptRequest",
           "1. createGroupAfterAcceptRequest(ownerId, requesterId, postId, 'Nhóm')",
           "Tạo room_groups với ownerId, memberIds=[ownerId,requesterId], postId, status='active'.",
           "ownerId:'A'\nrequesterId:'B'\npostId:'post1'"),
        tc("TC_097", "RoomGroupRepository", "getUserRoomGroups array-contains",
           "1. getUserRoomGroups('userA')",
           "Query memberIds ARRAY-CONTAINS 'userA'.",
           "userId:'userA'"),
        tc("TC_098", "RoomGroupRepository", "disbandGroup update status",
           "1. disbandGroup('group1')",
           "Update status='disbanded'.",
           "groupId:'group1'"),
        tc("TC_099", "UserProfileRepository", "getUserProfile tồn tại→UserModel",
           "1. getUserProfile('user1')\n2. Doc tồn tại",
           "Trả về UserModel.",
           "uid:'user1'"),
        tc("TC_100", "UserProfileRepository", "getUserProfile null nếu ko tồn tại",
           "1. getUserProfile('fake')",
           "null.",
           "uid:'fake'"),
        tc("TC_101", "UserProfileRepository", "updateHabits set habits+criteria",
           "1. updateHabits(uid, ['clean'], ['quiet'])\n2. profileCompleted=true",
           "Set habits, roommateCriteria, profileCompleted=true.",
           "uid:'user1'\nhabits:['clean']\ncriteria:['quiet']"),
        tc("TC_102", "UserNameCache", "profileStream userId mới tạo listener",
           "1. profileStream('user1') lần đầu\n2. Ref count=1",
           "Tạo Firestore listener mới.",
           "userId:'user1'"),
        tc("TC_103", "UserNameCache", "profileStream đã cache dùng lại",
           "1. profileStream('user1') lần 2\n2. Ref count=2",
           "Stream cũ. Không tạo listener mới.",
           "userId:'user1' (đã cache)"),
    ]),
]

create_sheet(wb, "02 - Repositories", "UNIT TESTS — REPOSITORIES", UNIT_BG, repos_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 3: VIEWMODELS
# ═══════════════════════════════════════════════════════════════════════════════
viewmodel_subs = [
    ("AuthViewModel", "1F5C99", [
        tc("TC_104", "AuthViewModel", "login thành công trả về role",
           "1. login(email, password)\n2. Repository.login thành công\n3. getUserRole→'user'",
           "Trả về 'user'. isLoading=false. errorMessage=null.",
           "email:'test@ex.com'\npassword:'Test@1234'"),
        tc("TC_105", "AuthViewModel", "login FirebaseAuthException map lỗi",
           "1. Repository.login throw FirebaseAuthException(code:'wrong-password')",
           "setError('Mật khẩu không đúng').",
           "FirebaseAuthException code:'wrong-password'"),
        tc("TC_106", "AuthViewModel", "signInWithGoogle banned→logout",
           "1. signInWithGoogle thành công\n2. getUserRole→'banned'",
           "Gọi logout(). setError('Tài khoản đã bị khóa').",
           "role:'banned'"),
        tc("TC_107", "AuthViewModel", "Google cancel→setError(null)",
           "1. PlatformException(code:'sign_in_canceled')",
           "setError(null).",
           "PlatformException\ncode:'sign_in_canceled'"),
        tc("TC_108", "AuthViewModel", "logout guarded ko gọi 2 lần",
           "1. logout() lần 1\n2. logout() lần 2 (đang xử lý)",
           "Lần 2 bỏ qua (_isLoggingOut=true).",
           "—"),
        tc("TC_109", "AuthViewModel", "dispose hủy subscription",
           "1. dispose()",
           "_authSubscription.cancel() được gọi.",
           "—"),
    ]),
    ("PostListViewModel / PostViewModel", "1F5C99", [
        tc("TC_110", "PostListViewModel", "applyFilter reset+subscribe lại",
           "1. applyFilter(filter mới)",
           "_posts=[]. _lastCursor=null. Subscribe first page.",
           "Filter mới"),
        tc("TC_111", "PostListViewModel", "filteredPosts lọc keyword in-memory",
           "1. _posts có 3 posts\n2. keyword='phòng'\n3. filteredPosts",
           "Chỉ posts có title/location/district/province chứa 'phòng'.",
           "keyword:'phòng'\n3 posts, 1 match"),
        tc("TC_112", "PostListViewModel", "loadMore khi có cursor",
           "1. _hasMore=true, _lastCursor!=null\n2. loadMore()",
           "Gọi repository.loadMorePosts. _posts thêm. isLoadingMore=false.",
           "Trang 1 đã load"),
        tc("TC_113", "PostListViewModel", "loadMore đang loading→skip",
           "1. _isLoadingMore=true\n2. loadMore()",
           "Bỏ qua.",
           "_isLoadingMore: true"),
        tc("TC_114", "PostViewModel", "createPost validation fail price=null",
           "1. priceText='abc'→int.tryParse=null\n2. createPost",
           "setError('Vui lòng nhập đầy đủ'). false.",
           "priceText:'abc'"),
        tc("TC_115", "PostViewModel", "createPost validation fail empty title",
           "1. title.trim()=''\n2. createPost",
           "setError. false.",
           "title:''"),
        tc("TC_116", "PostViewModel", "createPost thành công",
           "1. Validation pass\n2. Repository.createPost thành công",
           "true. isLoading=false.",
           "Đầy đủ hợp lệ"),
        tc("TC_117", "PostViewModel", "deletePost thành công",
           "1. deletePost('post1')\n2. Repository thành công",
           "true. isLoading=false.",
           "postId:'post1'"),
    ]),
    ("ExpenseViewModel", "1F5C99", [
        tc("TC_118", "ExpenseViewModel", "calculateSplit equal chia đều",
           "1. amount=600000, paidBy='A', participants=['A','B','C']\n2. splitType=equal",
           "B→A=200000, C→A=200000.",
           "amount:600000\npaidBy:'A'\nparticipants:['A','B','C']"),
        tc("TC_119", "ExpenseViewModel", "calculateSplit custom validation fail",
           "1. amount=500000, customSplits {'B':200000,'C':200000}\n2. Tổng=400000≠500000",
           "Throw 'Tổng phần chia không bằng tổng chi phí'.",
           "customSplits tổng 400000≠500000"),
        tc("TC_120", "ExpenseViewModel", "calculateSplit paidBy là tất cả→[]",
           "1. paidBy='A', participants=['A']\n2. NonPayers=[]",
           "Trả về [].",
           "paidBy:'A'\nparticipants:['A']"),
        tc("TC_121", "ExpenseViewModel", "addExpense thành công",
           "1. addExpense đầy đủ\n2. Repository.addExpenseWithShares thành công",
           "true. setLoading(false).",
           "Expense đầy đủ"),
        tc("TC_122", "ExpenseViewModel", "loadNetDebtSummary tính net",
           "1. A→B=500, B→A=200\n2. loadNetDebtSummary\n3. netDebts",
           "B→A net=300. NetDebtEntry(fromUserId:'B', toUserId:'A', netAmount:300).",
           "gross: A→B=500, B→A=200"),
        tc("TC_123", "ExpenseViewModel", "monthlyTotal sum",
           "1. _monthlyExpenses=[exp1(300k), exp2(200k)]\n2. monthlyTotal",
           "500000.0.",
           "2 expenses"),
        tc("TC_124", "ExpenseViewModel", "spendByMember map",
           "1. exp1 paidBy='A'=300k, exp2 paidBy='A'=200k\n2. spendByMember(['A','B'])",
           "{'A':500000.0, 'B':0}.",
           "memberIds:['A','B']"),
    ]),
    ("Chat / Roommate / RoomGroup / Profile ViewModels", "1F5C99", [
        tc("TC_125", "ChatViewModel", "sendMessage empty→false",
           "1. text='   '\n2. text.trim().isEmpty=true",
           "false. Không gọi repository.",
           "text:'   '"),
        tc("TC_126", "ChatViewModel", "sendMessage thành công→true",
           "1. text='Hello'\n2. Repository thành công",
           "true. isSending=false.",
           "text:'Hello'"),
        tc("TC_127", "ChatViewModel", "markAsRead ko throw khi lỗi",
           "1. Repository.markAsRead throw\n2. markAsRead('conv1')",
           "Bắt exception. DebugPrint. Không throw.",
           "conversationId:'conv1'\nFirebase error"),
        tc("TC_128", "RoommateRequestViewModel", "pendingCount đếm đúng",
           "1. _receivedRequests: 3 pending, 2 accepted\n2. pendingCount",
           "3.",
           "5 requests, 3 pending"),
        tc("TC_129", "RoommateRequestViewModel", "ensureReceivedRequestsListening idempotent",
           "1. Đã listen\n2. Gọi lại",
           "Không tạo subscription mới.",
           "Đã có subscription"),
        tc("TC_130", "RoomGroupViewModel", "disbandGroup update local",
           "1. group1 status='active'\n2. disbandGroup('group1') thành công",
           "group1.status='disbanded'.",
           "groupId:'group1'"),
        tc("TC_131", "UserProfileViewModel", "getUserProfile cache trong 5 phút",
           "1. Gọi lần 1→repository\n2. Gọi lần 2 trong 5 phút",
           "Lần 2 từ cache. Không gọi repository.",
           "uid:'user1'\ncache<5 phút"),
    ]),
]

create_sheet(wb, "03 - ViewModels", "UNIT TESTS — VIEWMODELS", UNIT_BG, viewmodel_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 4: UTILITIES
# ═══════════════════════════════════════════════════════════════════════════════
utils_subs = [
    ("RoommateMatchHelper", "1F5C99", [
        tc("TC_132", "RoommateMatchHelper", "matchPercentage 100% identical",
           "1. currentHabits=targetHabits=['clean','no_smoking']\n2. currentCriteria=targetCriteria=['quiet']",
           "100.",
           "Habits & criteria identical"),
        tc("TC_133", "RoommateMatchHelper", "matchPercentage 0% no match",
           "1. current=['clean'], target=['messy']\n2. criteria khác nhau",
           "0.",
           "Không match"),
        tc("TC_134", "RoommateMatchHelper", "budget overlap score 100",
           "1. current='2-3tr', target='2.5-4tr'\n2. Overlap=[2.5,3]",
           "Budget overlap→100.",
           "Budget overlap"),
        tc("TC_135", "RoommateMatchHelper", "budget gap distance ratio",
           "1. current='2-3tr', target='4-5tr'\n2. gap=1tr, ref=5tr, ratio=0.2",
           "gap/reference=0.20→60 points.",
           "Budget gap 1tr"),
        tc("TC_136", "RoommateMatchHelper", "conflict penalty sleep_early vs stay_up_late",
           "1. currentHabits chứa 'sleep_early'\n2. target chứa 'stay_up_late'",
           "Penalty+=10. Tổng clamp 0-30.",
           "'sleep_early' vs 'stay_up_late'"),
        tc("TC_137", "RoommateMatchHelper", "_parseBudgetRange '2 - 3 triệu'",
           "1. _parseBudgetRange('2 - 3 triệu')",
           "_NumericRange(2000000,3000000).",
           "Input:'2 - 3 triệu'"),
        tc("TC_138", "RoommateMatchHelper", "_parseBudgetRange empty→null",
           "1. _parseBudgetRange('')",
           "null.",
           "Input:''"),
        tc("TC_139", "RoommateMatchHelper", "_normalizedSet trim+lowercase+filter",
           "1. [' Clean ', 'NO_SMOKING', '']\n2. normalizedSet",
           "{'clean','no_smoking'}. Empty bị loại.",
           "[' Clean ', 'NO_SMOKING', '']"),
    ]),
    ("HomeFormatters", "1F5C99", [
        tc("TC_140", "HomeFormatters", "formatLastTwoWords 'Nguyễn Văn A'",
           "1. formatLastTwoWords('Nguyễn Văn A')",
           "'Văn A'.",
           "fullName:'Nguyễn Văn A'"),
        tc("TC_141", "HomeFormatters", "formatLastTwoWords 1 từ 'Admin'",
           "1. formatLastTwoWords('Admin')",
           "'Admin'.",
           "fullName:'Admin'"),
        tc("TC_142", "HomeFormatters", "formatLastTwoWords rỗng→'Người dùng'",
           "1. formatLastTwoWords('')",
           "'Người dùng'.",
           "fullName:''"),
        tc("TC_143", "HomeFormatters", "formatReadableAddress ưu tiên fullAddress",
           "1. fullAddress='123 Đường A'\n2. preferredLocation='Q1'\n3. district='Q2'",
           "'123 Đường A'.",
           "Có fullAddress"),
        tc("TC_144", "HomeFormatters", "formatReadableAddress fallback district+province",
           "1. fullAddress='', preferredLocation=''\n2. district='Quận 1', province='TP HCM'",
           "'Quận 1, TP HCM'.",
           "Chỉ district+province"),
        tc("TC_145", "HomeFormatters", "formatReadableAddress all empty",
           "1. Tất cả rỗng",
           "'Chưa cập nhật địa chỉ'.",
           "All empty"),
    ]),
    ("FormatUtils", "1F5C99", [
        tc("TC_146", "FormatUtils", "formatMoney 0→'0đ'",
           "1. formatMoney(0)",
           "'0đ'.",
           "Input:0"),
        tc("TC_147", "FormatUtils", "formatMoney 1000→'1.000đ'",
           "1. formatMoney(1000)",
           "'1.000đ'.",
           "Input:1000"),
        tc("TC_148", "FormatUtils", "formatMoney 1500000→'1.500.000đ'",
           "1. formatMoney(1500000)",
           "'1.500.000đ'.",
           "Input:1500000"),
        tc("TC_149", "FormatUtils", "formatMoney 100000000→'100.000.000đ'",
           "1. formatMoney(100000000)",
           "'100.000.000đ'.",
           "Input:100000000"),
        tc("TC_243", "FormatUtils", "Số lớn 9999999999",
           "1. formatMoney(9999999999)",
           "'9.999.999.999đ'.",
           "Input:9999999999"),
        tc("TC_244", "FormatUtils", "Số thập phân 1500.7",
           "1. formatMoney(1500.7)",
           "toStringAsFixed(0)→'1500'→'1.500đ'.",
           "Input:1500.7"),
    ]),
    ("Mappers / Constants / Logout", "1F5C99", [
        tc("TC_150", "HabitRoommateCriteriaMapper", "mapHabitsToRoommateCriteria có mapping",
           "1. mapHabitsToRoommateCriteria(['clean','no_smoking'])",
           "['Giữ gìn vệ sinh', 'Không hút thuốc'].",
           "habits:['clean','no_smoking']"),
        tc("TC_151", "HabitRoommateCriteriaMapper", "mapHabitsToRoommateCriteria rỗng",
           "1. mapHabitsToRoommateCriteria([])",
           "[].",
           "habits:[]"),
        tc("TC_152", "LogoutHelper", "performLogout reset tất cả providers",
           "1. performLogout(context)\n2. Kiểm tra các provider",
           "filterVm.resetFilter. roommateVm.resetSession. chatVm.clearSession. authVm.logout. Navigate LoginScreen.",
           "Context có đủ providers"),
        tc("TC_153", "RoomFilterData", "provinces 9 tỉnh/thành",
           "1. RoomFilterData.provinces",
           "9 tỉnh/thành đúng.",
           "length==9"),
        tc("TC_154", "RoomFilterData", "roomTypes 11 loại",
           "1. RoomFilterData.roomTypes",
           "11 loại: Phòng trọ, Căn hộ/Chung cư, Studio...",
           "length==11"),
        tc("TC_155", "RoomFilterData", "amenities 10 tiện ích",
           "1. RoomFilterData.amenities",
           "10: Máy lạnh, Thú cưng, Ban công, Bếp...",
           "length==10"),
    ]),
]

create_sheet(wb, "04 - Utilities", "UNIT TESTS — UTILITIES", UNIT_BG, utils_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 5: WIDGETS
# ═══════════════════════════════════════════════════════════════════════════════
widget_subs = [
    ("Core Widgets", "1F5C99", [
        tc("TC_156", "AppAvatar", "Có avatarUrl→Image.network",
           "1. AppAvatar(name='A', avatarUrl='https://ex.com/a.jpg')",
           "Image.network với borderRadius circle.",
           "avatarUrl:'https://ex.com/a.jpg'"),
        tc("TC_157", "AppAvatar", "Không avatarUrl→initials fallback",
           "1. AppAvatar(name='Nguyen Van A', avatarUrl=null)",
           "Container gradient với initials 'NA'.",
           "name:'Nguyen Van A'\navatarUrl:null"),
        tc("TC_158", "AppAvatar", "showBorder thêm border",
           "1. AppAvatar(showBorder:true)",
           "Container wrap border primary, width+4.",
           "showBorder:true"),
        tc("TC_159", "AppPrimaryButton", "Idle hiển thị label",
           "1. AppPrimaryButton(label:'Đăng nhập', isLoading:false)",
           "Text 'Đăng nhập'. key='label'.",
           "label:'Đăng nhập'\nisLoading:false"),
        tc("TC_160", "AppPrimaryButton", "Loading hiển thị spinner+disabled",
           "1. AppPrimaryButton(label:'Đăng nhập', isLoading:true)",
           "CircularProgressIndicator. key='loading'. onTap ko gọi.",
           "isLoading:true"),
        tc("TC_161", "AppPrimaryButton", "Disabled ko gọi onTap",
           "1. isLoading=true\n2. Nhấn nút",
           "onTap không được gọi.",
           "isLoading:true"),
        tc("TC_162", "AppLoadingState", "Hiển thị spinner+message",
           "1. AppLoadingState(message:'Đang tải...')",
           "Center: CircularProgressIndicator + Text.",
           "message:'Đang tải...'"),
        tc("TC_163", "AppEmptyState", "Hiển thị icon+title+message+optional action",
           "1. AppEmptyState(title='Ko có', message='Chưa có gì', actionLabel='Thử lại', onAction=...())",
           "Icon circle. Title. Message. Nếu actionLabel+onAction→AppPrimaryButton.",
           "Có action"),
        tc("TC_164", "AppErrorState", "Hiển thị error+retry button",
           "1. AppErrorState(title='Lỗi', message='Có lỗi', onRetry=...())",
           "Icon error circle. Title 'Lỗi'. Message. Nút 'Thử lại'.",
           "Có onRetry"),
        tc("TC_165", "StatusBadge", "Màu sắc đúng theo type",
           "1. BadgeType.success\n2. BadgeType.danger\n3. BadgeType.info",
           "Mỗi type bg+fg khác nhau.",
           "Các BadgeType"),
    ]),
    ("Feature Widgets", "1F5C99", [
        tc("TC_166", "AuthTextField", "TextFormField decoration đúng",
           "1. AuthTextField(hintText:'Email', prefixIcon:Icons.email, validator:(v)=>v==null?'required':null)",
           "InputDecoration: hintText, prefixIcon, fillColor, border radius 16.",
           "hintText:'Email'\nprefixIcon:Icons.email"),
        tc("TC_167", "SocialLoginButton", "Image+text+border 999",
           "1. SocialLoginButton(text:'Google', imagePath:'assets/google.png')",
           "Image.asset 22 + Text. Container borderRadius 999.",
           "text:'Google'\nimagePath:'assets/google.png'"),
        tc("TC_168", "HomeHeaderWidget", "Greeting theo giờ",
           "1. <12→'Chào buổi sáng'\n2. 12-18→'Chào buổi chiều'\n3. >18→'Chào buổi tối'",
           "Text greeting đúng giờ.",
           "Các khung giờ"),
        tc("TC_169", "HomeHeaderWidget", "Filter summary hiển thị",
           "1. filter.hasActiveFilters=true\n2. filter.summaryText='Q1 • 2-3tr'",
           "Hiển thị summary. Icon tune container primary.",
           "filter có active"),
        tc("TC_170", "PostsFeedSectionWidget", "Loading→shimmer",
           "1. vm.isLoading=true\n2. Render",
           "_PostCardShimmer.",
           "isLoading:true"),
        tc("TC_171", "PostsFeedSectionWidget", "Empty→_InlineMessage",
           "1. vm.filteredPosts=[]\n2. vm.isLoading=false",
           "_InlineMessage 'Chưa có bài đăng nào'.",
           "posts:[]"),
        tc("TC_172", "PostsFeedSectionWidget", "Có posts→_FeaturedPostCard",
           "1. vm.filteredPosts có 3 posts\n2. Render",
           "3 _FeaturedPostCard: image, title, price, amenities, button.",
           "3 posts"),
        tc("TC_173", "SuggestedProfilesSectionWidget", "Loading→shimmer",
           "1. snapshot.connectionState=ConnectionState.waiting",
           "_ProfileCardShimmer.",
           "Loading"),
        tc("TC_174", "SuggestedProfilesSectionWidget", "Empty→_InlineMessage",
           "1. profiles=[]\n2. Render",
           "'Chưa có hồ sơ phù hợp'.",
           "profiles:[]"),
        tc("TC_175", "SuggestedProfilesSectionWidget", "Có profiles→horizontal list",
           "1. 6 profiles\n2. Render",
           "SizedBox 300. ListView horizontal. Card: avatar, name, match%, habits, buttons.",
           "6 profiles"),
        tc("TC_176", "SuggestedProfilesSectionWidget", "Invited→check icon",
           "1. isInvited(userId)=true\n2. Render card",
           "Icon check_rounded. Màu success. Ko onInviteTap.",
           "isInvited:true"),
        tc("TC_241", "AppAvatar", "Tên ký tự đặc biệt",
           "1. name='Nguyễn Văn A (123)'\n2. _initials",
           "Initials:'NA'.",
           "name:'Nguyễn Văn A (123)'"),
        tc("TC_242", "AppAvatar", "Tên 1 ký tự",
           "1. name='A'\n2. _initials",
           "Initials:'A'.",
           "name:'A'"),
    ]),
]

create_sheet(wb, "05 - Widgets", "WIDGET TESTS", UNIT_BG, widget_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 6: FRONT-END QA
# ═══════════════════════════════════════════════════════════════════════════════
fe_subs = [
    ("AUTH — Login Screen", "1F5C99", [
        tc("TC_177", "Login Screen", "Đăng nhập thành công (Positive)",
           "1. Nhập email hợp lệ\n2. Nhập password đúng\n3. Nhấn Đăng nhập",
           "App chuyển HomeScreen. Không lỗi.",
           "Email:test@example.com\nPassword:Test@1234",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_178", "Login Screen", "Sai mật khẩu (Negative)",
           "1. Nhập email đúng\n2. Password sai\n3. Nhấn Đăng nhập",
           "SnackBar: 'Mật khẩu không đúng'.",
           "Email:test@example.com\nPassword:WrongPass",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_179", "Login Screen", "Google thành công (Positive)",
           "1. Nhấn 'Tiếp tục với Google'\n2. Chọn tài khoản",
           "Chuyển HomeScreen hoặc CompleteProfileIntroScreen.",
           "Tài khoản Google hợp lệ",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_180", "Login Screen", "Google huỷ (Negative)",
           "1. Nhấn Google\n2. Đóng dialog",
           "Giữ Login. Không lỗi.",
           "(Huỷ dialog)",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("AUTH — Register & Forgot Password", "1F5C99", [
        tc("TC_181", "Register Screen", "Đăng ký thành công",
           "1. Điền đầy đủ\n2. Nhấn Đăng ký",
           "Tài khoản tạo. Chuyển CompleteProfileIntroScreen.",
           "FullName:Nguyen Van A\nEmail:new@test.com\nPassword:Test@1234",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_182", "Register Screen", "Email đã tồn tại",
           "1. Email đã đăng ký\n2. Nhấn Đăng ký",
           "Lỗi: email-already-in-use.",
           "Email đã tồn tại",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_183", "Forgot Password", "Gửi email reset thành công",
           "1. Nhập email\n2. Nhấn gửi",
           "Chuyển CheckEmailScreen. Firebase gửi email.",
           "Email:test@example.com",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_184", "Forgot Password", "Email không tồn tại",
           "1. Email chưa đăng ký\n2. Nhấn gửi",
           "Lỗi: user-not-found.",
           "Email:fake@test.com",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("PROFILE", "1F5C99", [
        tc("TC_185", "Complete Profile", "Hoàn thành profile lần đầu (Positive)",
           "1. Sau đăng ký\n2. Điền đầy đủ + chọn habits\n3. Hoàn thành",
           "profileCompleted=true. Chuyển UserHomeScreen.",
           "FullName:Nguyen Van A\nPhone:0901234567\nAge:23",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_186", "Complete Profile", "Bỏ qua ko điền (Negative)",
           "1. Không điền gì\n2. Nhấn Hoàn thành",
           "Thông báo field bắt buộc.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_187", "Edit Profile", "Cập nhật thông tin",
           "1. UserProfileScreen→Edit\n2. Thay đổi họ tên+phone\n3. Lưu",
           "Firestore cập nhật. Profile hiển thị mới.",
           "NewName:Tran Thi B\nNewPhone:0912345678",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_188", "Edit Habits", "Chọn thói quen",
           "1. EditHabitsScreen\n2. Chọn clean, no_smoking\n3. Lưu",
           "Habits lưu Firestore.",
           "Habits:[clean,no_smoking]",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("POST", "1F5C99", [
        tc("TC_189", "Create Post", "Tạo bài đăng hợp lệ",
           "1. Điền đầy đủ\n2. Upload ảnh\n3. Nhấn Đăng",
           "Post tạo Firestore. Xuất hiện danh sách. Ảnh Cloudinary.",
           "Title:Phòng trọ Q3\nPrice:3500000\nArea:25",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_190", "Create Post", "Bỏ trống title (Negative)",
           "1. Điền đủ trừ title\n2. Nhấn Đăng",
           "Thông báo: title bắt buộc.",
           "Title:(trống)",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_191", "Create Post", "Price=0 (Negative)",
           "1. price=0\n2. Nhấn Đăng",
           "Thông báo: price>0.",
           "Price:0",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_192", "Create Post", "Không upload ảnh (Negative)",
           "1. Không chọn ảnh\n2. Nhấn Đăng",
           "Thông báo: cần ít nhất 1 ảnh.",
           "imageUrls:[]",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_193", "Edit Post", "Sửa bài của chính mình",
           "1. MyPosts→Edit\n2. Thay đổi price\n3. Lưu",
           "Post cập nhật Firestore.",
           "NewPrice:4000000",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_194", "Delete Post", "Xóa bài của chính mình",
           "1. MyPosts→Delete\n2. Xác nhận",
           "Post xóa Firestore. Biến mất.",
           "postId hợp lệ",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("HOME & ROOMMATE REQUEST", "1F5C99", [
        tc("TC_195", "Home Screen", "Posts Feed + Suggested Profiles",
           "1. Đăng nhập\n2. Quan sát Home",
           "Posts feed + suggested profiles hiển thị.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_196", "Home Screen", "Tab navigation 5 tabs",
           "1. Nhấn lần lượt các tab",
           "Mỗi tab đúng nội dung. Active tab highlight.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_197", "Room Search Filter", "Lọc theo tỉnh/thành",
           "1. Mở filter\n2. Chọn 'Hồ Chí Minh'\n3. Áp dụng",
           "Chỉ post province='Hồ Chí Minh'.",
           "Province:Hồ Chí Minh",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_198", "Room Search Filter", "Lọc khoảng giá",
           "1. min=2tr, max=5tr\n2. Áp dụng",
           "Chỉ post price trong [2tr,5tr].",
           "min:2000000\nmax:5000000",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_199", "Room Search Filter", "Lọc kết hợp nhiều điều kiện",
           "1. Province+RoomType+price range\n2. Áp dụng",
           "Thỏa mãn tất cả điều kiện.",
           "Province:Hà Nội\nRoomType:Phòng trọ\nmax:3tr",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_200", "Room Search Filter", "Không kết quả (Negative)",
           "1. Giá 1-1000đ\n2. Áp dụng",
           "Empty: 'Không tìm thấy kết quả'.",
           "min:1\nmax:1000",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_201", "Send Request", "Gửi yêu cầu ghép phòng (Positive)",
           "1. PostDetail bài người khác\n2. Nhấn Gửi yêu cầu\n3. Nhập lời nhắn\n4. Xác nhận",
           "Request tạo Firestore status=pending.",
           "Post của người khác",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_202", "Received Requests", "Xem danh sách yêu cầu",
           "1. Đăng nhập chủ bài\n2. Tab Requests→Received",
           "Danh sách: avatar, tên, status badge.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_203", "Received Requests", "Chấp nhận→tạo group",
           "1. Nhấn Chấp nhận\n2. Kiểm tra RoomGroup",
           "Status→accepted. Group tạo. Cả 2 vào group.",
           "requestId hợp lệ",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_204", "Received Requests", "Từ chối yêu cầu",
           "1. Nhấn Từ chối",
           "Status→rejected.",
           "requestId hợp lệ",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("ROOM GROUP & EXPENSE", "1F5C99", [
        tc("TC_205", "Room Group", "Xem thông tin nhóm",
           "1. Tab Room Group",
           "Tên nhóm, thành viên, post, trạng thái.",
           "Là member của group",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_206", "Room Group", "Owner cập nhật tên",
           "1. Là owner\n2. Cập nhật tên",
           "Firestore cập nhật.",
           "Tên mới:'Nhóm phòng Q3 2026'",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_207", "Add Expense", "Chia đều (Positive)",
           "1. Title+amount\n2. Split=equal\n3. Chọn 2 participants\n4. Lưu",
           "Expense tạo. Mỗi người=amount/2.",
           "Title:Tiền điện\nAmount:500000\n2 participants",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_208", "Add Expense", "Chia custom (Positive)",
           "1. Split=custom\n2. Nhập splits\n3. Tổng=amount",
           "Shares với amountOwed custom.",
           "Amount:600000\nA:200000, B:400000",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_209", "Add Expense", "Amount=0 (Negative)",
           "1. amount=0\n2. Lưu",
           "Thông báo: amount>0.",
           "Amount:0",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_210", "Debt Screen", "Xem tổng nợ",
           "1. Vào DebtScreen",
           "A nợ B X đồng. Từ unpaid shares.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_211", "Debt Screen", "Đánh dấu đã trả",
           "1. Nhấn Đã trả\n2. Xác nhận",
           "isPaid=true. Biến mất.",
           "share của currentUser",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_212", "Monthly Summary", "Xem biểu đồ tháng",
           "1. MonthlySummaryScreen\n2. Chọn tháng",
           "Biểu đồ fl_chart. Tổng đúng.",
           "Tháng 5/2026",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_213", "Monthly Summary", "Tháng không data",
           "1. Chọn tháng chưa có expense",
           "Empty: 'Chưa có chi phí'.",
           "Tháng mới",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("CHAT", "1F5C99", [
        tc("TC_214", "Chat List", "Xem danh sách hội thoại",
           "1. Tab Chat",
           "Avatar, tên, lastMessage, thời gian, unread badge.",
           "Có ≥1 conversation",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_215", "Chat List", "Danh sách trống",
           "1. Tài khoản mới",
           "Empty: 'Chưa có cuộc trò chuyện'.",
           "Tài khoản mới",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_216", "Chat Detail", "Gửi tin nhắn (Positive)",
           "1. Mở conversation\n2. Gõ tin\n3. Nhấn gửi",
           "Tin phía phải. RTDB nhận data.",
           "Text:'Xin chào'",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_217", "Chat Detail", "Real-time nhận tin",
           "1. 2 thiết bị cùng chat\n2. Gửi từ A",
           "B nhận ngay.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_218", "Chat Detail", "Gửi tin trống (Negative)",
           "1. Input trống\n2. Nhấn gửi",
           "Không gửi. Nút disabled.",
           "Text:(trống)",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_219", "Chat Detail", "Đánh dấu đã đọc",
           "1. Có tin chưa đọc\n2. Mở chat",
           "unreadCount=0. Badge biến mất.",
           "unreadCount>0",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
]

create_sheet(wb, "06 - Frontend QA", "FRONT-END QA TESTS", FRONT_END_BG, fe_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 7: BACK-END RULES
# ═══════════════════════════════════════════════════════════════════════════════
be_subs = [
    ("Firestore Security Rules", "833C00", [
        tc("TC_220", "Firestore Rules — Users", "Đọc user chưa đăng nhập (Security)",
           "1. Unauthenticated\n2. Read /users/{uid}",
           "Error: permission-denied.",
           "Unauthenticated","","","Untested","","","","","",""),
        tc("TC_221", "Firestore Rules — Users", "Xóa user (Security)",
           "1. Gọi delete /users/{uid}",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
        tc("TC_222", "Firestore Rules — Posts", "Tạo post ownerId giả mạo (Security)",
           "1. ownerId != auth.uid\n2. Create post",
           "Error: permission-denied.",
           "ownerId:fake_uid","","","Untested","","","","","",""),
        tc("TC_223", "Firestore Rules — Posts", "Đọc post chưa đăng nhập (Security)",
           "1. Unauthenticated\n2. Read /posts/{id}",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
        tc("TC_224", "Firestore Rules — Requests", "Người ngoài đọc request (Security)",
           "1. User C ko phải requester/postOwner\n2. Read request",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
        tc("TC_225", "Firestore Rules — Requests", "Tạo request status!=pending (Security)",
           "1. status='accepted'\n2. Create request",
           "Error: permission-denied.",
           "status:accepted","","","Untested","","","","","",""),
        tc("TC_226", "Firestore Rules — Room Groups", "Xóa room group (Security)",
           "1. Delete /room_groups/{id}",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
        tc("TC_227", "Firestore Rules — Room Groups", "Người ngoài đọc group (Security)",
           "1. Read group không là member",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
        tc("TC_228", "Firestore Rules — Expense Shares", "Người khác update isPaid (Security)",
           "1. User != fromUserId\n2. Update expense_share",
           "Error: permission-denied.",
           "—","","","Untested","","","","","",""),
    ]),
]

create_sheet(wb, "07 - Backend Rules", "BACK-END / FIRESTORE RULES", BACK_END_BG, be_subs)

# ═══════════════════════════════════════════════════════════════════════════════
# SHEET 8: INTEGRATION E2E
# ═══════════════════════════════════════════════════════════════════════════════
e2e_subs = [
    ("End-to-End Flows", "375623", [
        tc("TC_229", "Auth→Profile Flow", "Đăng ký→hoàn thành profile→Home (E2E)",
           "1. Đăng ký mới\n2. CompleteProfileIntroScreen\n3. Hoàn thành profile\n4. UserHomeScreen",
           "profileCompleted=true. AuthGate đúng.",
           "Email mới",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_230", "Post→Request→Group", "Đăng bài→nhận request→chấp nhận→group (E2E)",
           "1. User A tạo bài\n2. User B gửi request\n3. A chấp nhận\n4. Group tạo",
           "Group tồn tại. A và B là member.",
           "2 tài khoản test",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_231", "Group→Expense→Debt", "Vào group→thêm expense→kiểm tra debt (E2E)",
           "1. Vào group\n2. Expense 600K chia đều 2 người\n3. DebtScreen",
           "B nợ A 300K. isPaid=false.",
           "Amount:600000\nPayer:A",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_232", "Request→Chat", "Gửi request→chat (E2E)",
           "1. B gửi request post A\n2. A chấp nhận\n3. B mở Chat với A\n4. Gửi tin",
           "Tin gửi thành công. RTDB có data. A nhận.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_233", "Session", "Logout→về LoginScreen",
           "1. Đang ở HomeScreen\n2. Logout",
           "Session xóa. Về LoginScreen.",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_234", "Session", "App restart giữ session",
           "1. Đăng nhập\n2. Đóng app\n3. Mở lại",
           "Tự vào HomeScreen (Firebase persistence).",
           "—",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_235", "Cloudinary", "Upload ảnh mạng chậm",
           "1. Tạo bài 3 ảnh\n2. Giả lập 3G\n3. Nhấn Đăng",
           "Loading indicator. Upload xong→post tạo.",
           "3 ảnh, mạng 3G",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
        tc("TC_236", "Offline", "Mất kết nối khi dùng app",
           "1. Đang dùng app\n2. Tắt mạng\n3. Thử thêm expense",
           "Lỗi mạng. App ko crash.",
           "Network: offline",
           "","","Untested","Untested","Untested","Untested","Untested","Untested",""),
    ]),
    ("Admin Dashboard", "375623", [
        tc("TC_237", "Admin Dashboard", "Admin login vào dashboard",
           "1. role='admin'\n2. Vào Admin Dashboard",
           "Dashboard: thống kê, user list, post management.",
           "Tài khoản admin",
           "","","Untested","Untested","","","","",""),
        tc("TC_238", "Admin Dashboard", "User thường ko vào được admin",
           "1. role='user'\n2. Cố truy cập admin",
           "Firestore Rules từ chối.",
           "role:user",
           "","","Untested","Untested","","","","",""),
        tc("TC_239", "Admin Dashboard", "Ban/unban user",
           "1. Admin→user management\n2. Ban user\n3. Unban",
           "User role→'banned'/'user'.",
           "User ID hợp lệ",
           "","","Untested","Untested","","","","",""),
        tc("TC_240", "Admin Dashboard", "Xem thống kê tổng quan",
           "1. Admin→dashboard statistics",
           "Tổng users, posts, groups, biểu đồ.",
           "—",
           "","","Untested","Untested","","","","",""),
    ]),
]

create_sheet(wb, "08 - Integration E2E", "INTEGRATION (E2E FLOWS)", INTEG_BG, e2e_subs)

# ── Save ──
out_path = r"E:\RoomMateApp\roommateapp\docs\RoomMateApp_TestCases_v3.xlsx"
wb.save(out_path)
print(f"Saved -> {out_path}")
print(f"Total: 8 sheets, 244 test cases")
